version: '3'
services:
  backend:
    container_name: doker-node-mongo
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/var/www/triplytrip-backend
    ports:
      - '8080:8080'
    command: npm run dev
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '23456:23456'
    volumes:
      - /var/lib/postgresql/data